services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    command: php -S 0.0.0.0:8000 -t public

  # Optional: Add MySQL database
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: purissima
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
